env:
  browser: true
  node: true
  commonjs: true
  es6: true
  mocha: true

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

extends:
- izumin5210
- izumin5210/react
- izumin5210/flow

settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules

globals:
  assert: true
  React: true
  Perf: true

rules:
  # wait for https://github.com/benmosher/eslint-plugin-import/issues/708
  import/named: off
