version: '2'

services:
  db:
    image: postgres:9.6.2-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data

  puma:
    build:
      context: .
    command: ["bin/rails", "server", "--binding", "0.0.0.0"]
    environment:
    - RAILS_ENV=development
    - PORT=3000
    env_file: .env
    volumes:
    - ./app:/app/app
    - ./bin:/app/bin
    - ./config:/app/config
    - ./db:/app/db
    - ./lib:/app/lib
    - ./public:/app/public
    - ./spec:/app/spec
    - ./Gemfile:/app/Gemfile
    - ./Gemfile.lock:/app/Gemfile.lock
    - ./Rakefile:/app/Rakefile
    - ./config.ru:/app/config.ru
    - ./.rspec:/app/.rspec
    - bundle_install:/app/vendor/bundle
    - bundle:/app/.bundle
    ports:
    - 3000:3000
    depends_on:
    - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
