version: '2'

services:
  db:
    image: postgres:9.6.2-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  rails:
    build:
      context: .
    command: ["bin/rails", "server", "--binding", "0.0.0.0"]
    env_file: .env
    volumes:
    - bundle:/app/.bundle
    - bundle_install:/app/vendor/bundle
    - node_modules:/app/node_modules
    - .:/app
    ports:
    - 3000:3000
    depends_on:
    - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
