version: '2'

services:
  db:
    image: postgres:9.6.2-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  rails:
    build:
      context: .
    command: ["bin/rails", "server", "--binding", "0.0.0.0"]
    env_file: .env
    volumes:
    - ./app:/app/app
    - ./bin:/app/bin
    - ./config:/app/config
    - ./db:/app/db
    - ./lib:/app/lib
    - ./public:/app/public
    - ./spec:/app/spec
    - ./vendor:/app/vendor
    - ./Gemfile:/app/Gemfile
    - ./Gemfile.lock:/app/Gemfile.lock
    - ./Rakefile:/app/Rakefile
    - ./config.ru:/app/config.ru
    - ./package.json:/app/package.json
    - ./yarn.lock:/app/yarn.lock
    - ./.babelrc:/app/.babelrc
    - ./.postcssrc.yml:/app/.postcssrc.yml
    - ./.rspec:/app/.rspec
    - bundle_install:/app/vendor/bundle
    - bundle:/app/.bundle
    - node_modules:/app/node_modules
    ports:
    - 3000:3000
    depends_on:
    - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
